### ISSUE TITLE
[Feature Request] add red dot to desktop icon while recording?

### ISSUE THREAD

**Issue by deadpahn** [alexkdeveloper/recorder#15]
Thanks for the awesome app. It's simple and captures desktop audio phenomenally. 

One skill issue I keep running into is I forget it is recording and it's running in the background, sometimes for days! Any chance we can see a red dot for recording in the taskbar icon? And or maybe a toggle to stop recording after a set amount of time?

Thanks

**Comment by alexkdeveloper** [comment]
Hi!

In the next release, a timer will be added to complete the recording. The necessary changes have already been made to the application repository.
