### ISSUE TITLE
[Feature Request] Trash file

### ISSUE THREAD

**Issue by begin-theadventure** [alexkdeveloper/recorder#21]
instead of `Delete file` (forever).
This would be really useful, for example, in case of a mistake or change of mind.
Could be either an option ( ⋯ -> Settings -> `Trash files` with the description under it `Moves files to the trash instead of deleting them forever`) or a default.

**Comment by alexkdeveloper** [comment]
This will be implemented in the next version.

**Comment by begin-theadventure** [comment]
That was really quick, thank you!
