### ISSUE TITLE
No sound in all of the recording

### ISSUE THREAD

**Issue by MaledictYtb** [alexkdeveloper/recorder#22]
Hello, 
I have installed this app from Flathub on my fedora kinoite PC, but there is no audio from the recordings. 
I think the app doesn't use my microphone since there is still no sound when opening the recording with another app

**Comment by alexkdeveloper** [comment]
Hi!
Please explain in more detail.
How did you install this app?
Have you banned application components?

**Comment by alexkdeveloper** [comment]
Access to pulseaudio is specified in the application manifest.

If you disable it, the app will not be able to play or record audio.

**Comment by alexkdeveloper** [comment]
https://github.com/flathub/com.github.alexkdeveloper.recorder/blob/master/com.github.alexkdeveloper.recorder.json

**Comment by MaledictYtb** [comment]
I've installed this app from flathub and in flatseal pulseaudio is enabled

**Comment by alexkdeveloper** [comment]
I think I can guess what's going on.
Have you probably tried recording with a microphone?
The app does not use a microphone for recording. It is designed to record the system audio stream. That is, to record music from streaming services such as YouTube. Just turn on the music track and launch the app. This information is contained in the description of the application.

**Comment by alexkdeveloper** [comment]
It is better to use another application to record from a microphone. For example, using this:
https://flathub.org/apps/com.github.ryonakano.reco

**Comment by MaledictYtb** [comment]
Oh ok sorry. I thought it was for recording audio with the microphone.
